// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmergencyServerClient.proto

package com.proto.EmergencyServerClient;

public final class EmergencyServerClientOuterClass {
  private EmergencyServerClientOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmergencyServerClient_Emergency_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmergencyServerClient_Emergency_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmergencyServerClient_EmergencyManyTimesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmergencyServerClient_EmergencyManyTimesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmergencyServerClient_EmergencyManyTimesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmergencyServerClient_EmergencyManyTimesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmergencyServerClient_LongEmergencyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmergencyServerClient_LongEmergencyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmergencyServerClient_LongEmergencyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmergencyServerClient_LongEmergencyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmergencyServerClient_ErrorHandlingSCRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmergencyServerClient_ErrorHandlingSCRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmergencyServerClient_ErrorHandlingSCResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmergencyServerClient_ErrorHandlingSCResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033EmergencyServerClient.proto\022\025Emergency" +
      "ServerClient\"\217\001\n\tEmergencyUnary\022\031\n\021PatientFir" +
      "st_name\030\001 \001(\t\022\030\n\020PatientLast_name\030\002 \001(\t\022" +
      "\013\n\003age\030\003 \001(\005\022\017\n\007Address\030\004 \001(\t\022\033\n\023high_Bl" +
      "ood_pressure\030\005 \001(\t\022\022\n\nMedication\030\006 \001(\t\"P" +
      "\n\031EmergencyManyTimesRequest\0223\n\temergency" +
      "\030\001 \001(\0132 .EmergencyServerClient.EmergencyUnary" +
      "\",\n\032EmergencyManyTimesResponse\022\016\n\006result" +
      "\030\001 \001(\t\"K\n\024LongEmergencyRequest\0223\n\temerge" +
      "ncy\030\001 \001(\0132 .EmergencyServerClient.Emerge" +
      "ncy\"\'\n\025LongEmergencyResponse\022\016\n\006result\030\001" +
      " \001(\t\",\n\026ErrorHandlingSCRequest\022\022\n\nMedica" +
      "tion\030\001 \001(\t\")\n\027ErrorHandlingSCResponse\022\016\n" +
      "\006result\030\001 \001(\t2\372\002\n\025EmergencyServerClient\022" +
      "}\n\022EmergencyManyTimes\0220.EmergencyServerC" +
      "lient.EmergencyManyTimesRequest\0321.Emerge" +
      "ncyServerClient.EmergencyManyTimesRespon" +
      "se\"\0000\001\022n\n\rLongEmergency\022+.EmergencyServe" +
      "rClient.LongEmergencyRequest\032,.EmergencyUnary" +
      "ServerClient.LongEmergencyResponse\"\000(\001\022r" +
      "\n\017ErrorHandlingSC\022-.EmergencyServerClien" +
      "t.ErrorHandlingSCRequest\032..EmergencyServ" +
      "erClient.ErrorHandlingSCResponse\"\000B#\n\037co" +
      "m.proto.EmergencyServerClientP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_EmergencyServerClient_Emergency_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EmergencyServerClient_Emergency_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmergencyServerClient_Emergency_descriptor,
        new java.lang.String[] { "PatientFirstName", "PatientLastName", "Age", "Address", "HighBloodPressure", "Medication", });
    internal_static_EmergencyServerClient_EmergencyManyTimesRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EmergencyServerClient_EmergencyManyTimesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmergencyServerClient_EmergencyManyTimesRequest_descriptor,
        new java.lang.String[] { "EmergencyUnary", });
    internal_static_EmergencyServerClient_EmergencyManyTimesResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_EmergencyServerClient_EmergencyManyTimesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmergencyServerClient_EmergencyManyTimesResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_EmergencyServerClient_LongEmergencyRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_EmergencyServerClient_LongEmergencyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmergencyServerClient_LongEmergencyRequest_descriptor,
        new java.lang.String[] { "EmergencyUnary", });
    internal_static_EmergencyServerClient_LongEmergencyResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_EmergencyServerClient_LongEmergencyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmergencyServerClient_LongEmergencyResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_EmergencyServerClient_ErrorHandlingSCRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_EmergencyServerClient_ErrorHandlingSCRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmergencyServerClient_ErrorHandlingSCRequest_descriptor,
        new java.lang.String[] { "Medication", });
    internal_static_EmergencyServerClient_ErrorHandlingSCResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_EmergencyServerClient_ErrorHandlingSCResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmergencyServerClient_ErrorHandlingSCResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
