// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmergencyServerClient.proto

package com.proto.EmergencyServerClient;

public interface ErrorHandlingSCRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmergencyServerClient.ErrorHandlingSCRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Medication = 1;</code>
   */
  java.lang.String getMedication();
  /**
   * <code>string Medication = 1;</code>
   */
  com.google.protobuf.ByteString
      getMedicationBytes();
}
