// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmergencyServerClient.proto

package com.proto.EmergencyServerClient;

public interface LongEmergencyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmergencyServerClient.LongEmergencyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.EmergencyServerClient.EmergencyUnary emergency = 1;</code>
   */
  boolean hasEmergency();
  /**
   * <code>.EmergencyServerClient.EmergencyUnary emergency = 1;</code>
   */
  com.proto.EmergencyServerClient.Emergency getEmergency();
  /**
   * <code>.EmergencyServerClient.EmergencyUnary emergency = 1;</code>
   */
  com.proto.EmergencyServerClient.EmergencyOrBuilder getEmergencyOrBuilder();
}
