// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmergencyBidi.proto

package com.proto.EmergencyBidirectionl;

public interface EmergencyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmergencyBidirectionl.EmergencyUnary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string high_Blood_pressure = 1;</code>
   */
  java.lang.String getHighBloodPressure();
  /**
   * <code>string high_Blood_pressure = 1;</code>
   */
  com.google.protobuf.ByteString
      getHighBloodPressureBytes();

  /**
   * <code>string Treatment = 2;</code>
   */
  java.lang.String getTreatment();
  /**
   * <code>string Treatment = 2;</code>
   */
  com.google.protobuf.ByteString
      getTreatmentBytes();
}
