// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmergencyBidi.proto

package com.proto.EmergencyBidirectionl;

public interface EmergencyMultiRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmergencyBidirectionl.EmergencyMultiRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.EmergencyBidirectionl.Emergency emergency = 1;</code>
   */
  boolean hasEmergency();
  /**
   * <code>.EmergencyBidirectionl.Emergency emergency = 1;</code>
   */
  com.proto.EmergencyBidirectionl.Emergency getEmergency();
  /**
   * <code>.EmergencyBidirectionl.Emergency emergency = 1;</code>
   */
  com.proto.EmergencyBidirectionl.EmergencyOrBuilder getEmergencyOrBuilder();
}
