// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmergencyBidi.proto

package com.proto.EmergencyBidirectionl;

/**
 * <pre>
 *create messagens error handling
 * </pre>
 *
 * Protobuf type {@code EmergencyBidirectionl.ErrorHandlingBidiRequest}
 */
public  final class ErrorHandlingBidiRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:EmergencyBidirectionl.ErrorHandlingBidiRequest)
    ErrorHandlingBidiRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ErrorHandlingBidiRequest.newBuilder() to construct.
  private ErrorHandlingBidiRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ErrorHandlingBidiRequest() {
    treatment_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ErrorHandlingBidiRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            treatment_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.proto.EmergencyBidirectionl.EmergencyBidi.internal_static_EmergencyBidirectionl_ErrorHandlingBidiRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.proto.EmergencyBidirectionl.EmergencyBidi.internal_static_EmergencyBidirectionl_ErrorHandlingBidiRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest.class, com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest.Builder.class);
  }

  public static final int TREATMENT_FIELD_NUMBER = 1;
  private volatile java.lang.Object treatment_;
  /**
   * <code>string Treatment = 1;</code>
   */
  public java.lang.String getTreatment() {
    java.lang.Object ref = treatment_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      treatment_ = s;
      return s;
    }
  }
  /**
   * <code>string Treatment = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTreatmentBytes() {
    java.lang.Object ref = treatment_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      treatment_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTreatmentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, treatment_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTreatmentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, treatment_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest)) {
      return super.equals(obj);
    }
    com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest other = (com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest) obj;

    boolean result = true;
    result = result && getTreatment()
        .equals(other.getTreatment());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TREATMENT_FIELD_NUMBER;
    hash = (53 * hash) + getTreatment().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *create messagens error handling
   * </pre>
   *
   * Protobuf type {@code EmergencyBidirectionl.ErrorHandlingBidiRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EmergencyBidirectionl.ErrorHandlingBidiRequest)
      com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.EmergencyBidirectionl.EmergencyBidi.internal_static_EmergencyBidirectionl_ErrorHandlingBidiRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.EmergencyBidirectionl.EmergencyBidi.internal_static_EmergencyBidirectionl_ErrorHandlingBidiRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest.class, com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest.Builder.class);
    }

    // Construct using com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      treatment_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.proto.EmergencyBidirectionl.EmergencyBidi.internal_static_EmergencyBidirectionl_ErrorHandlingBidiRequest_descriptor;
    }

    @java.lang.Override
    public com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest getDefaultInstanceForType() {
      return com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest build() {
      com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest buildPartial() {
      com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest result = new com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest(this);
      result.treatment_ = treatment_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest) {
        return mergeFrom((com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest other) {
      if (other == com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest.getDefaultInstance()) return this;
      if (!other.getTreatment().isEmpty()) {
        treatment_ = other.treatment_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object treatment_ = "";
    /**
     * <code>string Treatment = 1;</code>
     */
    public java.lang.String getTreatment() {
      java.lang.Object ref = treatment_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        treatment_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Treatment = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTreatmentBytes() {
      java.lang.Object ref = treatment_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        treatment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Treatment = 1;</code>
     */
    public Builder setTreatment(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      treatment_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Treatment = 1;</code>
     */
    public Builder clearTreatment() {
      
      treatment_ = getDefaultInstance().getTreatment();
      onChanged();
      return this;
    }
    /**
     * <code>string Treatment = 1;</code>
     */
    public Builder setTreatmentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      treatment_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:EmergencyBidirectionl.ErrorHandlingBidiRequest)
  }

  // @@protoc_insertion_point(class_scope:EmergencyBidirectionl.ErrorHandlingBidiRequest)
  private static final com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest();
  }

  public static com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ErrorHandlingBidiRequest>
      PARSER = new com.google.protobuf.AbstractParser<ErrorHandlingBidiRequest>() {
    @java.lang.Override
    public ErrorHandlingBidiRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ErrorHandlingBidiRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ErrorHandlingBidiRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ErrorHandlingBidiRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.proto.EmergencyBidirectionl.ErrorHandlingBidiRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

