// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmergencyBidi.proto

package com.proto.EmergencyBidirectionl;

public interface ErrorHandlingBidiRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmergencyBidirectionl.ErrorHandlingBidiRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Treatment = 1;</code>
   */
  java.lang.String getTreatment();
  /**
   * <code>string Treatment = 1;</code>
   */
  com.google.protobuf.ByteString
      getTreatmentBytes();
}
