// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmergencyUnary.proto

package com.proto.EmergencyUnary;

/**
 * <pre>
 *Create the EmergencyUnary  Request
 * </pre>
 *
 * Protobuf type {@code EmergencyUnary.EmergencyRequest}
 */
public  final class EmergencyRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:EmergencyUnary.EmergencyRequest)
    EmergencyRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EmergencyRequest.newBuilder() to construct.
  private EmergencyRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EmergencyRequest() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EmergencyRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.proto.EmergencyUnary.Emergency.Builder subBuilder = null;
            if (emergency_ != null) {
              subBuilder = emergency_.toBuilder();
            }
            emergency_ = input.readMessage(com.proto.EmergencyUnary.Emergency.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(emergency_);
              emergency_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.proto.EmergencyUnary.EmergencyOuterClass.internal_static_Emergency_EmergencyRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.proto.EmergencyUnary.EmergencyOuterClass.internal_static_Emergency_EmergencyRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.proto.EmergencyUnary.EmergencyRequest.class, com.proto.EmergencyUnary.EmergencyRequest.Builder.class);
  }

  public static final int EMERGENCY_FIELD_NUMBER = 1;
  private com.proto.EmergencyUnary.Emergency emergency_;
  /**
   * <code>.EmergencyUnary.EmergencyUnary emergency = 1;</code>
   */
  public boolean hasEmergency() {
    return emergency_ != null;
  }
  /**
   * <code>.EmergencyUnary.EmergencyUnary emergency = 1;</code>
   */
  public com.proto.EmergencyUnary.Emergency getEmergency() {
    return emergency_ == null ? com.proto.EmergencyUnary.Emergency.getDefaultInstance() : emergency_;
  }
  /**
   * <code>.EmergencyUnary.EmergencyUnary emergency = 1;</code>
   */
  public com.proto.EmergencyUnary.EmergencyOrBuilder getEmergencyOrBuilder() {
    return getEmergency();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (emergency_ != null) {
      output.writeMessage(1, getEmergency());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (emergency_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getEmergency());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.proto.EmergencyUnary.EmergencyRequest)) {
      return super.equals(obj);
    }
    com.proto.EmergencyUnary.EmergencyRequest other = (com.proto.EmergencyUnary.EmergencyRequest) obj;

    boolean result = true;
    result = result && (hasEmergency() == other.hasEmergency());
    if (hasEmergency()) {
      result = result && getEmergency()
          .equals(other.getEmergency());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasEmergency()) {
      hash = (37 * hash) + EMERGENCY_FIELD_NUMBER;
      hash = (53 * hash) + getEmergency().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.proto.EmergencyUnary.EmergencyRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.EmergencyUnary.EmergencyRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.EmergencyUnary.EmergencyRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.EmergencyUnary.EmergencyRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.EmergencyUnary.EmergencyRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.EmergencyUnary.EmergencyRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.EmergencyUnary.EmergencyRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.proto.EmergencyUnary.EmergencyRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.proto.EmergencyUnary.EmergencyRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.proto.EmergencyUnary.EmergencyRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.proto.EmergencyUnary.EmergencyRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.proto.EmergencyUnary.EmergencyRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.proto.EmergencyUnary.EmergencyRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *Create the EmergencyUnary  Request
   * </pre>
   *
   * Protobuf type {@code EmergencyUnary.EmergencyRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EmergencyUnary.EmergencyRequest)
      com.proto.EmergencyUnary.EmergencyRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.EmergencyUnary.EmergencyOuterClass.internal_static_Emergency_EmergencyRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.EmergencyUnary.EmergencyOuterClass.internal_static_Emergency_EmergencyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.proto.EmergencyUnary.EmergencyRequest.class, com.proto.EmergencyUnary.EmergencyRequest.Builder.class);
    }

    // Construct using com.proto.EmergencyUnary.EmergencyRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (emergencyBuilder_ == null) {
        emergency_ = null;
      } else {
        emergency_ = null;
        emergencyBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.proto.EmergencyUnary.EmergencyOuterClass.internal_static_Emergency_EmergencyRequest_descriptor;
    }

    @java.lang.Override
    public com.proto.EmergencyUnary.EmergencyRequest getDefaultInstanceForType() {
      return com.proto.EmergencyUnary.EmergencyRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.proto.EmergencyUnary.EmergencyRequest build() {
      com.proto.EmergencyUnary.EmergencyRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.proto.EmergencyUnary.EmergencyRequest buildPartial() {
      com.proto.EmergencyUnary.EmergencyRequest result = new com.proto.EmergencyUnary.EmergencyRequest(this);
      if (emergencyBuilder_ == null) {
        result.emergency_ = emergency_;
      } else {
        result.emergency_ = emergencyBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.proto.EmergencyUnary.EmergencyRequest) {
        return mergeFrom((com.proto.EmergencyUnary.EmergencyRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.proto.EmergencyUnary.EmergencyRequest other) {
      if (other == com.proto.EmergencyUnary.EmergencyRequest.getDefaultInstance()) return this;
      if (other.hasEmergency()) {
        mergeEmergency(other.getEmergency());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.proto.EmergencyUnary.EmergencyRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.proto.EmergencyUnary.EmergencyRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.proto.EmergencyUnary.Emergency emergency_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.proto.EmergencyUnary.Emergency, com.proto.EmergencyUnary.Emergency.Builder, com.proto.EmergencyUnary.EmergencyOrBuilder> emergencyBuilder_;
    /**
     * <code>.EmergencyUnary.EmergencyUnary emergency = 1;</code>
     */
    public boolean hasEmergency() {
      return emergencyBuilder_ != null || emergency_ != null;
    }
    /**
     * <code>.EmergencyUnary.EmergencyUnary emergency = 1;</code>
     */
    public com.proto.EmergencyUnary.Emergency getEmergency() {
      if (emergencyBuilder_ == null) {
        return emergency_ == null ? com.proto.EmergencyUnary.Emergency.getDefaultInstance() : emergency_;
      } else {
        return emergencyBuilder_.getMessage();
      }
    }
    /**
     * <code>.EmergencyUnary.EmergencyUnary emergency = 1;</code>
     */
    public Builder setEmergency(com.proto.EmergencyUnary.Emergency value) {
      if (emergencyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        emergency_ = value;
        onChanged();
      } else {
        emergencyBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.EmergencyUnary.EmergencyUnary emergency = 1;</code>
     */
    public Builder setEmergency(
        com.proto.EmergencyUnary.Emergency.Builder builderForValue) {
      if (emergencyBuilder_ == null) {
        emergency_ = builderForValue.build();
        onChanged();
      } else {
        emergencyBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.EmergencyUnary.EmergencyUnary emergency = 1;</code>
     */
    public Builder mergeEmergency(com.proto.EmergencyUnary.Emergency value) {
      if (emergencyBuilder_ == null) {
        if (emergency_ != null) {
          emergency_ =
            com.proto.EmergencyUnary.Emergency.newBuilder(emergency_).mergeFrom(value).buildPartial();
        } else {
          emergency_ = value;
        }
        onChanged();
      } else {
        emergencyBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.EmergencyUnary.EmergencyUnary emergency = 1;</code>
     */
    public Builder clearEmergency() {
      if (emergencyBuilder_ == null) {
        emergency_ = null;
        onChanged();
      } else {
        emergency_ = null;
        emergencyBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.EmergencyUnary.EmergencyUnary emergency = 1;</code>
     */
    public com.proto.EmergencyUnary.Emergency.Builder getEmergencyBuilder() {
      
      onChanged();
      return getEmergencyFieldBuilder().getBuilder();
    }
    /**
     * <code>.EmergencyUnary.EmergencyUnary emergency = 1;</code>
     */
    public com.proto.EmergencyUnary.EmergencyOrBuilder getEmergencyOrBuilder() {
      if (emergencyBuilder_ != null) {
        return emergencyBuilder_.getMessageOrBuilder();
      } else {
        return emergency_ == null ?
            com.proto.EmergencyUnary.Emergency.getDefaultInstance() : emergency_;
      }
    }
    /**
     * <code>.EmergencyUnary.EmergencyUnary emergency = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.proto.EmergencyUnary.Emergency, com.proto.EmergencyUnary.Emergency.Builder, com.proto.EmergencyUnary.EmergencyOrBuilder>
        getEmergencyFieldBuilder() {
      if (emergencyBuilder_ == null) {
        emergencyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.proto.EmergencyUnary.Emergency, com.proto.EmergencyUnary.Emergency.Builder, com.proto.EmergencyUnary.EmergencyOrBuilder>(
                getEmergency(),
                getParentForChildren(),
                isClean());
        emergency_ = null;
      }
      return emergencyBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:EmergencyUnary.EmergencyRequest)
  }

  // @@protoc_insertion_point(class_scope:EmergencyUnary.EmergencyRequest)
  private static final com.proto.EmergencyUnary.EmergencyRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.proto.EmergencyUnary.EmergencyRequest();
  }

  public static com.proto.EmergencyUnary.EmergencyRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EmergencyRequest>
      PARSER = new com.google.protobuf.AbstractParser<EmergencyRequest>() {
    @java.lang.Override
    public EmergencyRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EmergencyRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EmergencyRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EmergencyRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.proto.EmergencyUnary.EmergencyRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

