// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmergencyUnary.proto

package com.proto.EmergencyUnary;

public interface EmergencyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmergencyUnary.EmergencyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   */
  java.lang.String getResult();
  /**
   * <code>string result = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
