// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmergencyUnary.proto

package com.proto.EmergencyUnary;

public interface EmergencyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmergencyUnary.EmergencyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.EmergencyUnary.EmergencyUnary emergency = 1;</code>
   */
  boolean hasEmergency();
  /**
   * <code>.EmergencyUnary.EmergencyUnary emergency = 1;</code>
   */
  com.proto.EmergencyUnary.Emergency getEmergency();
  /**
   * <code>.EmergencyUnary.EmergencyUnary emergency = 1;</code>
   */
  com.proto.EmergencyUnary.EmergencyOrBuilder getEmergencyOrBuilder();
}
