// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Emergency.proto

package com.proto.EmergencyUnary;

public interface EmergencyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Emergency.Emergency)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string PatientFirst_name = 1;</code>
   */
  java.lang.String getPatientFirstName();
  /**
   * <code>string PatientFirst_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getPatientFirstNameBytes();

  /**
   * <code>string PatientLast_name = 2;</code>
   */
  java.lang.String getPatientLastName();
  /**
   * <code>string PatientLast_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getPatientLastNameBytes();

  /**
   * <code>int32 age = 3;</code>
   */
  int getAge();

  /**
   * <code>string Address = 4;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string Address = 4;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>double high_Blood_pressure = 5;</code>
   */
  double getHighBloodPressure();
}
