// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Emergency.proto

package com.proto.EmergencyUnary;

public final class EmergencyOuterClass {
  private EmergencyOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Emergency_Emergency_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Emergency_Emergency_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Emergency_EmergencyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Emergency_EmergencyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Emergency_EmergencyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Emergency_EmergencyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Emergency_ErrorHandlingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Emergency_ErrorHandlingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Emergency_ErrorHandlingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Emergency_ErrorHandlingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Emergency.proto\022\tEmergency\"{\n\tEmergenc" +
      "y\022\031\n\021PatientFirst_name\030\001 \001(\t\022\030\n\020PatientL" +
      "ast_name\030\002 \001(\t\022\013\n\003age\030\003 \001(\005\022\017\n\007Address\030\004" +
      " \001(\t\022\033\n\023high_Blood_pressure\030\005 \001(\001\";\n\020Eme" +
      "rgencyRequest\022\'\n\temergency\030\001 \001(\0132\024.Emerg" +
      "ency.Emergency\"#\n\021EmergencyResponse\022\016\n\006r" +
      "esult\030\001 \001(\t\"1\n\024ErrorHandlingRequest\022\031\n\021P" +
      "atientFirst_name\030\001 \001(\t\"\'\n\025ErrorHandlingR" +
      "esponse\022\016\n\006result\030\001 \001(\t2\262\001\n\020EmergencySer" +
      "vice\022H\n\tEmergency\022\033.Emergency.EmergencyR" +
      "equest\032\034.Emergency.EmergencyResponse\"\000\022T" +
      "\n\rErrorHandling\022\037.Emergency.ErrorHandlin" +
      "gRequest\032 .Emergency.ErrorHandlingRespon" +
      "se\"\000B\034\n\030com.proto.EmergencyUnaryP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Emergency_Emergency_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Emergency_Emergency_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Emergency_Emergency_descriptor,
        new java.lang.String[] { "PatientFirstName", "PatientLastName", "Age", "Address", "HighBloodPressure", });
    internal_static_Emergency_EmergencyRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Emergency_EmergencyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Emergency_EmergencyRequest_descriptor,
        new java.lang.String[] { "Emergency", });
    internal_static_Emergency_EmergencyResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Emergency_EmergencyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Emergency_EmergencyResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_Emergency_ErrorHandlingRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Emergency_ErrorHandlingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Emergency_ErrorHandlingRequest_descriptor,
        new java.lang.String[] { "PatientFirstName", });
    internal_static_Emergency_ErrorHandlingResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Emergency_ErrorHandlingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Emergency_ErrorHandlingResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
