// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmergencyUnary.proto

package com.proto.EmergencyUnary;

public interface ErrorHandlingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmergencyUnary.ErrorHandlingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string PatientFirst_name = 1;</code>
   */
  java.lang.String getPatientFirstName();
  /**
   * <code>string PatientFirst_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getPatientFirstNameBytes();
}
